name: HDocBuild_Push
on:
  # Triggers the workflow on push requests
  push:

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0 
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install hdoc-tools
        run: npm install hdoc-tools -g
            
      - name: Perform Validation
        id: hdocbuild
        run: |
          if result=`hdoc build 2>&1`; then
              printf "Build Success!\n\n"
              printf "$result"
              exit 0
          else
            valout=$(echo "$result" | awk '/Validation Output/,0')
            printf "Build Failed!\n\n-----------------------\n"
            printf "$valout"
            exit 1
          fi
          
      - name: Build Success
        if: success()
        run: echo "::notice::Build validation passed successfully."
